#theme: jekyll-theme-potato-hacker
title: Agent Skywalker👨‍💻:~#
description: Offensive Security.
show_downloads: false
show_repo: false

safe: true

plugins:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-seo-tag
  - some-other-jekyll-plugin
  - jekyll-twitter-plugin
  
gems:
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap
